fix(deploy): delete offending page
we'll have to recreate this one later, and investigate why it breaks the build
error:
info  - Generating static pages (0/6)

Error occurred prerendering page "/nl/zoeken/[slug]".
Read more: https://nextjs.org/docs/messages/prerender-error
Error: Invariant failed